import { defineField, defineType } from "sanity";

export const siteSettingsType = defineType({
  name: "siteSettings",
  title: "Site settings",
  type: "document",
  fields: [
    defineField({ name: "titleHu", type: "string" }),
    defineField({ name: "titleEn", type: "string" }),
    defineField({ name: "descriptionHu", type: "text", rows: 3 }),
    defineField({ name: "descriptionEn", type: "text", rows: 3 }),
    defineField({ name: "festivalStartDate", type: "date" }),
    defineField({ name: "festivalEndDate", type: "date" }),
    defineField({ name: "venueNameHu", type: "string" }),
    defineField({ name: "venueNameEn", type: "string" }),
    defineField({ name: "ticketUrlHu", type: "url" }),
    defineField({ name: "ticketUrlEn", type: "url" }),
    defineField({ name: "facebookUrl", type: "url" }),
    defineField({ name: "instagramUrl", type: "url" }),
    defineField({ name: "youtubeUrl", type: "url" }),
    defineField({ name: "contactEmail", type: "string" }),
    defineField({ name: "contactPhone", type: "string" }),
    defineField({ name: "volunteerTitleHu", type: "string" }),
    defineField({ name: "volunteerTitleEn", type: "string" }),
    defineField({ name: "volunteerDescriptionHu", type: "text", rows: 2 }),
    defineField({ name: "volunteerDescriptionEn", type: "text", rows: 2 }),
    defineField({ name: "volunteerButtonLabelHu", type: "string" }),
    defineField({ name: "volunteerButtonLabelEn", type: "string" }),
    defineField({ name: "volunteerUrl", type: "url" }),
    defineField({ name: "houseRulesPdf", type: "string" }),
    defineField({ name: "organizationName", type: "string" }),
    defineField({ name: "organizationUrl", type: "url" }),
    defineField({ name: "seo", type: "seo" }),
  ],
});
