import { defineField, defineType } from "sanity";

export const siteSettingsType = defineType({
  name: "siteSettings",
  title: "Site beállítások",
  type: "document",
  description:
    "Globális beállítások az oldalhoz: cím / leírás, fesztivál dátum, helyszín, kapcsolat, közösségi linkek. EGY példány lehet belőle.",
  fields: [
    defineField({ name: "titleHu", title: "Site cím (HU)", type: "string" }),
    defineField({ name: "titleEn", title: "Site cím (EN)", type: "string" }),
    defineField({ name: "descriptionHu", title: "Site leírás (HU)", type: "text", rows: 3 }),
    defineField({ name: "descriptionEn", title: "Site leírás (EN)", type: "text", rows: 3 }),
    defineField({ name: "festivalStartDate", title: "Fesztivál kezdete", type: "date" }),
    defineField({ name: "festivalEndDate", title: "Fesztivál vége", type: "date" }),
    defineField({ name: "venueNameHu", title: "Helyszín neve (HU)", type: "string" }),
    defineField({ name: "venueNameEn", title: "Helyszín neve (EN)", type: "string" }),
    defineField({ name: "ticketUrlHu", title: "Jegyvásárlás link (HU)", type: "url" }),
    defineField({ name: "ticketUrlEn", title: "Jegyvásárlás link (EN)", type: "url" }),
    defineField({ name: "facebookUrl", title: "Facebook URL", type: "url" }),
    defineField({ name: "instagramUrl", title: "Instagram URL", type: "url" }),
    defineField({ name: "youtubeUrl", title: "YouTube URL", type: "url" }),
    defineField({ name: "contactEmail", title: "Kapcsolat e-mail", type: "string" }),
    defineField({ name: "contactPhone", title: "Kapcsolat telefon", type: "string" }),
    defineField({
      name: "volunteerTitleHu",
      title: "Önkéntes szekció — cím (HU)",
      type: "string",
      description: "Jelenleg nem renderelődik az UI-on, fenntartva későbbi blokkhoz.",
    }),
    defineField({ name: "volunteerTitleEn", title: "Önkéntes szekció — cím (EN)", type: "string" }),
    defineField({
      name: "volunteerDescriptionHu",
      title: "Önkéntes szekció — leírás (HU)",
      type: "text",
      rows: 2,
      description: "Jelenleg nem renderelődik az UI-on.",
    }),
    defineField({ name: "volunteerDescriptionEn", title: "Önkéntes szekció — leírás (EN)", type: "text", rows: 2 }),
    defineField({
      name: "volunteerButtonLabelHu",
      title: "Önkéntes gomb felirata (HU)",
      type: "string",
      description: "A Kapcsolat oldalon megjelenő önkéntes gomb szövege.",
    }),
    defineField({ name: "volunteerButtonLabelEn", title: "Önkéntes gomb felirata (EN)", type: "string" }),
    defineField({ name: "volunteerUrl", title: "Önkéntes űrlap URL", type: "url" }),
    defineField({
      name: "houseRulesPdf",
      title: "Házirend PDF útvonal",
      type: "string",
      description: "Pl. /docs/hazirend.pdf — a Kapcsolat / Info oldalakon link.",
    }),
    defineField({ name: "organizationName", title: "Szervező neve", type: "string" }),
    defineField({ name: "organizationUrl", title: "Szervező URL", type: "url" }),
    defineField({ name: "seo", title: "Globális SEO (fallback)", type: "seo" }),
  ],
});
