import type {
  GalleryImage,
  RunningDistance,
  Sponsor,
  SponsorSection,
} from "@/lib/types";

export const BASE = {
  festivalDates: {
    hu: "2026. augusztus 6–9.",
    en: "Aug 6–9, 2026",
  },
  festivalYear: "2026",
  venue: {
    hu: "Domb Beach (Benkó Zoltán Szabadidőközpont)",
    en: "Domb Beach (Benkó Zoltán Recreation Centre)",
  },
  city: {
    hu: "Kecskemét",
    en: "Kecskemét, Hungary",
  },
  gps: "46.903819, 19.666032",
  mapImage: "/images/map/festival-map.jpg",

  ticketUrl: "https://jazzfovaros.jegy.hu/program/x-bohem-jazzfovaros-fesztival-berletek/",
  ticketUrlEn: "https://jazzfovaros.jegy.hu/?lang=en",

  socials: {
    facebook: "https://www.facebook.com/jazzfovaros",
    instagram: "https://www.instagram.com/jazzfovaros",
    youtube: "https://www.youtube.com/@jazzfovaros",
  },

  videoUrl: "https://www.youtube.com/embed/GEXbBkFjHC0",

  contact: {
    organizer: {
      hu: "JAZZFŐVÁROS Zenei Előadóművészeti és Rendezvényszervező Kft.",
      en: "JAZZ CAPITAL Ltd (JAZZFŐVÁROS Kft.)",
    },
    address: {
      hu: "6000 Kecskemét, Csabagyöngye u. 71.",
      en: "H-6000 Kecskemét, Csabagyöngye u. 71., Hungary",
    },
    email: "jazzfovaros@gmail.com",
    phone: "+36-20-960-7169",
    phone2: "+36-20-336-4620",
    phone2NameHu: "Adrienn",
    phone2En: "+36-20-369-2111",
    phone2NameEn: "Mariann",
    pressEmail: "sajt@bohemragtime.com",
    volunteerUrl:
      "https://docs.google.com/forms/d/e/1FAIpQLScN6dywhAxewWQfWvLtzphyTZ0NP75pFnmbO3nIbAfumbi6ZQ/viewform",
  },

  builtBy: "Mayoka",
  builtByUrl: "http://mayoka.hu",

  artists: [
    {
      name: "Dresch Mihály Quartet",
      genre: "Magyar Jazz",
      bio: "",
      image: "/images/artists/dresch.jpg",
      day: "friday",
      stage: "main",
      time: "21:00",
      origin: "Budapest, Magyarország",
    },
    {
      name: "Tigran Hamasyan",
      genre: "Contemporary Jazz",
      bio: "",
      image: "/images/artists/tigran.jpg",
      day: "saturday",
      stage: "main",
      time: "22:00",
      origin: "Jerevány, Örményország",
    },
    {
      name: "Borbély Mihály",
      genre: "World Jazz",
      bio: "",
      image: "/images/artists/borbely.jpg",
      day: "friday",
      stage: "club",
      time: "19:30",
      origin: "Magyarország",
    },
    {
      name: "GoGo Penguin",
      genre: "Jazz / Electronic",
      bio: "",
      image: "/images/artists/gogopenguin.jpg",
      day: "saturday",
      stage: "main",
      time: "20:00",
      origin: "Manchester, Egyesült Királyság",
    },
    {
      name: "Roby Lakatos & Ensemble",
      genre: "Gypsy Jazz / Classical",
      bio: "",
      image: "/images/artists/roby.jpg",
      day: "sunday",
      stage: "main",
      time: "20:30",
      origin: "Budapest, Magyarország",
    },
    {
      name: "Nils Petter Molvær",
      genre: "Nordic Jazz / Fusion",
      bio: "",
      image: "/images/artists/molvaer.jpg",
      day: "sunday",
      stage: "main",
      time: "22:00",
      origin: "Oslo, Norvégia",
    },
    {
      name: "Grencsó Kollektíva",
      genre: "Free Jazz / Avantgárd",
      bio: "",
      image: "/images/artists/grenco.jpg",
      day: "saturday",
      stage: "club",
      time: "21:30",
      origin: "Budapest, Magyarország",
    },
    {
      name: "Cory Henry & The Funk Apostles",
      genre: "Soul Jazz / Funk",
      bio: "",
      image: "/images/artists/cory.jpg",
      day: "friday",
      stage: "main",
      time: "22:30",
      origin: "New York, USA",
    },
  ],

  galleryImages: [
    { src: "/images/gallery/01.jpg", alt: "" },
    { src: "/images/gallery/02.jpg", alt: "" },
    { src: "/images/gallery/03.jpg", alt: "" },
    { src: "/images/gallery/04.jpg", alt: "" },
    { src: "/images/gallery/05.jpg", alt: "" },
    { src: "/images/gallery/06.jpg", alt: "" },
    { src: "/images/gallery/07.jpg", alt: "" },
    { src: "/images/gallery/08.jpg", alt: "" },
    { src: "/images/gallery/09.jpg", alt: "" },
    { src: "/images/gallery/10.jpg", alt: "" },
    { src: "/images/gallery/11.jpg", alt: "" },
    { src: "/images/gallery/12.jpg", alt: "" },
  ] as GalleryImage[],

  accommodation: {
    hotels: [
      {
        name: "Four Points by Sheraton Kecskemét",
        description: "",
        price: { hu: "19 950 Ft/fő/éjtől", en: "from HUF 19,950 / person / night" },
        distance: { hu: "15 perc sétára a fesztiváltól", en: "15 min walk from the festival" },
        bookingUrl: "https://www.marriott.com/en-us/hotels/kebfp-four-points-kecskemet/overview/",
        images: ["/images/accommodation/sheraton-1.jpg", "/images/accommodation/sheraton-2.jpg"],
        stars: 4,
      },
      {
        name: "Hotel Aqua",
        description: "",
        price: { hu: "20 500 Ft/fő/éjtől", en: "from HUF 20,500 / person / night" },
        distance: { hu: "5 perc sétára a fesztiváltól", en: "5 min walk from the festival" },
        bookingUrl: "https://aquahotel.hu",
        images: ["/images/accommodation/aqua-1.jpg", "/images/accommodation/aqua-2.jpg"],
        stars: 3,
      },
      {
        name: "Tó Kemping",
        description: "",
        price: { hu: "Kemping árak regisztráció alapján", en: "Camping rates on registration" },
        distance: { hu: "Közvetlenül a helyszín mellett", en: "Directly next to the venue" },
        bookingUrl: "https://tokemping.hu",
        images: ["/images/accommodation/tokemping-1.jpg"],
        stars: undefined,
      },
    ],
  },

  running: {
    date: { hu: "2025. augusztus 9., szombat", en: "Saturday, 9 August 2025" },
    time: "16:00",
    location: { hu: "Nagyvárosliget, Kecskemét", en: "Nagyvárosliget, Kecskemét" },
    entryUrl: "https://nevezes.hu/",
    entryDeadline: { hu: "2025. aug. 9., szombat 11:25, a Nagyvárosligetnél", en: "Saturday 9 Aug, 11:25 at Nagyvárosliget" },
    image: "/images/running/futas.jpg",
    contactEmail: "varga.peti@gmail.com",
    contactPhone: "+36 30 443 2117",
    contactUrl: "https://jazzfovaros.hu/futas",
    distances: [
      { label: "Felnőtt 5 km", distance: "5 km", fee: "1 500 Ft" },
      { label: "Felnőtt 2,5 km", distance: "2,5 km", fee: "1 000 Ft" },
      { label: "Gyerek (iskolás korig)", distance: "kb. 300 m", fee: "ingyenes" },
    ] as RunningDistance[],
  },

  camp: {
    videoUrl: "https://www.youtube.com/embed/V7hQehNWpYo",
    entryUrl: "https://pepitasummerswing.hu",
    supporters: [
      { name: "Nemzeti Kulturális Alap", logo: "/images/sponsors/nka.png", url: "https://nka.hu" },
      { name: "Neumann János Egyetem", logo: "/images/sponsors/nje.png", url: "https://nje.hu" },
      { name: "KEDO", logo: "/images/sponsors/kedo.png", url: "#" },
    ] as Sponsor[],
  },

  sponsors: {
    main: [
      { name: "Kecskemét Megyei Jogú Város", logo: "/images/sponsors/kecskemet.png", url: "https://kecskemet.hu" },
      { name: "Nemzeti Kulturális Alap", logo: "/images/sponsors/nka.png", url: "https://nka.hu" },
      { name: "STE", logo: "/images/sponsors/ste.png", url: "#" },
      { name: "Locall", logo: "/images/sponsors/locall.png", url: "#" },
      { name: "AlcoFer", logo: "/images/sponsors/alcofer.png", url: "#" },
      { name: "Cargoport", logo: "/images/sponsors/cargoport.png", url: "#" },
      { name: "NJE", logo: "/images/sponsors/nje.png", url: "https://nje.hu" },
      { name: "NL Netherlands", logo: "/images/sponsors/nl.png", url: "#" },
    ] as Sponsor[],
    sponsors: [
      { name: "Tesco", logo: "/images/sponsors/tesco.png", url: "#" },
      { name: "KEDO", logo: "/images/sponsors/kedo.png", url: "#" },
    ] as Sponsor[],
    partners: [
      { name: "Bartók Rádió", logo: "/images/sponsors/bartok.png", url: "#" },
      { name: "hirus.hu", logo: "/images/sponsors/hirus.png", url: "https://hirus.hu" },
      { name: "Axon", logo: "/images/sponsors/axon.png", url: "#" },
      { name: "Füredi", logo: "/images/sponsors/furedi.png", url: "#" },
      { name: "DTKH", logo: "/images/sponsors/dtkh.png", url: "#" },
      { name: "Gépész", logo: "/images/sponsors/gepesz.png", url: "#" },
      { name: "Tiszafüred", logo: "/images/sponsors/tiszafured.png", url: "#" },
      { name: "Zafiras", logo: "/images/sponsors/zafiras.png", url: "#" },
      { name: "LS", logo: "/images/sponsors/ls.png", url: "#" },
      { name: "Borona", logo: "/images/sponsors/borona.png", url: "#" },
      { name: "Beematec", logo: "/images/sponsors/beematec.png", url: "#" },
      { name: "Termostar", logo: "/images/sponsors/termostar.png", url: "#" },
      { name: "Simon Otthon", logo: "/images/sponsors/simon.png", url: "#" },
      { name: "Zöldség Sziget", logo: "/images/sponsors/zoldsziget.png", url: "#" },
      { name: "Veterán", logo: "/images/sponsors/veteran.png", url: "#" },
      { name: "Kecskeméti Lovasklub", logo: "/images/sponsors/lovas.png", url: "#" },
      { name: "Palotás", logo: "/images/sponsors/palotas.png", url: "#" },
    ] as Sponsor[],
  } as SponsorSection,
};
